/*******************************************************************************
 * Copyright (c) 2019, 2020 Sebastian Palarus
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v20.html
 *
 * Contributors:
 *     Sebastian Palarus - initial API and implementation
 *******************************************************************************/
package org.sodeac.common.jdbc.classicmodelcars;

import org.sodeac.common.typedtree.BranchNodeMetaModel;
import org.sodeac.common.typedtree.BranchNodeType;
import org.sodeac.common.typedtree.LeafNodeType;
import org.sodeac.common.typedtree.ModelRegistry;
import org.sodeac.common.typedtree.annotation.SQLColumn;
import org.sodeac.common.typedtree.annotation.SQLPrimaryKey;
import org.sodeac.common.typedtree.annotation.SQLTable;

@SQLTable(name="ORDERDETAILS")
public class OrderDetailNodeType extends BranchNodeMetaModel
{
	static{ModelRegistry.getBranchNodeMetaModel(OrderDetailNodeType.class);}
	
	@SQLColumn(name="ID")
	@SQLPrimaryKey(autoGenerated=true)
	public static volatile LeafNodeType<OrderDetailNodeType,Integer> ORDERDETAILID;
	
	@SQLColumn(name="ORDERLINENUMBER")
	public static volatile LeafNodeType<OrderDetailNodeType,Integer> ORDERDETAILORDERLINENUMBER;
	
	@SQLColumn(name="PRICEEACH")
	public static volatile LeafNodeType<OrderDetailNodeType,Double> ORDERDETAILPRICEEACH;
	
	@SQLColumn(name="QUANTITYORDERED")
	public static volatile LeafNodeType<OrderDetailNodeType,Integer> ORDERDETAILQUANTITYORDERED;
	
	@SQLColumn(name="PRODUCTCODE")
	public static volatile BranchNodeType<OrderDetailNodeType,ProductNodeType> PRODUCT;
}
