/*******************************************************************************
 * Copyright (c) 2019, 2020 Sebastian Palarus
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v20.html
 *
 * Contributors:
 *     Sebastian Palarus - initial API and implementation
 *******************************************************************************/
package org.sodeac.common.jdbc.classicmodelcars;

import java.util.Date;

import org.sodeac.common.typedtree.BranchNodeMetaModel;
import org.sodeac.common.typedtree.LeafNodeType;
import org.sodeac.common.typedtree.ModelRegistry;
import org.sodeac.common.typedtree.annotation.SQLColumn;
import org.sodeac.common.typedtree.annotation.SQLColumn.SQLColumnType;
import org.sodeac.common.typedtree.annotation.SQLPrimaryKey;
import org.sodeac.common.typedtree.annotation.SQLTable;

@SQLTable(name="PAYMENTS")
public class PaymentNodeType extends BranchNodeMetaModel
{
	static{ModelRegistry.getBranchNodeMetaModel(PaymentNodeType.class);}	
	
	@SQLColumn(name="ID")
	@SQLPrimaryKey(autoGenerated=true)
	public static volatile LeafNodeType<PaymentNodeType,Integer> PAYMENTID;
	
	@SQLColumn(name="AMOUNT")
	public static volatile LeafNodeType<PaymentNodeType,Double> PAYMENTAMOUNT;
	
	@SQLColumn(name="CHECKNUMBER")
	public static volatile LeafNodeType<PaymentNodeType,String> PAYMENTCHECKNUMBER;
	
	@SQLColumn(name="PAYMENTDATE",type=SQLColumnType.DATE)
	public static volatile LeafNodeType<PaymentNodeType,Date> PAYMENTDATE;
}
